# Generated by Django 5.0.1 on 2024-06-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0.0, upload_to='C:/Users/kayra/ecommercial/static/img'),
            preserve_default=False,
        ),
    ]
